import Head from 'next/head'
import Image from 'next/image'
import { Inter } from '@next/font/google'
import styles from '../styles/Home.module.css'
import { Dispatch, SetStateAction, useEffect, useState } from 'react'
import QueryCard from '../components/QueryCard'
import queries from '../lib/queries.json'
import { insertLineBreaks } from '../lib/helpers'

const inter = Inter({ subsets: ['latin'] })

export type state = {
  prompt: string
  SQL: string
  data: any[]
}

export type store = [state, Dispatch<SetStateAction<state>>]


const defaultState = {
  prompt: '',
  SQL: '',
  data: []
}

export default function Home() {
  const store = useState<state>(defaultState)
  const [{prompt, SQL, data}, setState] = store
  
  
  const handleSQL = async (SQL: string) => {

    const resp = await fetch('/api/lens', {
      method: "POST",
      body: JSON.stringify({ SQL }),
    })
    let response = await resp.json()
    if(resp.status != 200) return console.error('error', response)
    console.log('SQL resp', response)
    setState(prevState => ({...prevState, data: response?.results}))
  }

  const handlePrompt = async () => { 
    if(!prompt) return
    console.log('fetching with prompt:', prompt)
    setState(prevState => ({...prevState, data: [], SQL: 'loading...'}))
    const resp = await fetch('/api/genSQL', {
      method: "POST",
      body: JSON.stringify({ prompt }),
    })
    if(resp.status != 200) return console.error('error', resp)
    let response = await resp.json()
    console.log(response)
    const SQL = insertLineBreaks("SELECT " + response.data.choices[0].text)
    console.log(SQL)
    setState(prevState => ({...prevState, SQL: SQL}))
    await handleSQL(SQL)
  }

  return (
    <>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <div className='text-center'>
        <div className='max-w-2xl mx-auto'>
          <h1 className='text-3xl'>Text 2 SQL for Lens</h1>
          <div>
            <label>
              <input type="text" value={prompt} onChange={(e) => setState(pS => ({...pS, prompt: e.target.value}))} className='border-2 border-gray-300 rounded-md p-2 w-96' />
            </label>
            <button className='rounded-md bg-blue-500 text-white p-2' onClick={handlePrompt}>Search</button>
          </div>
          {SQL ? 
            <div className='text-base text-left m-2 whitespace-pre-line'>{SQL}</div> 
          : null}
          <br/><br/><br/>
          {data.length ? data.map(thing => JSON.stringify(thing)) : null}

          {queries.map((query, index) => <QueryCard key={index} text={query.text} store={store}/>)}

        </div>
      </div>
    </>
  )
}
